version: 2

base_image: &base_image
  image: circleci/node:8.9.4

job_common: &job_common
  docker:
    - <<: *base_image

save: &save
  save_cache:
    key: code-{{ .Revision }}
    paths:
      - .
      # save the git commit and ssh config
      - ".git"
      - "~/.ssh"

restore: &restore
  restore_cache:
    key: code-{{ .Revision }}

machine:
  services:
    - docker

jobs:
  lockfile_update:
    <<: *job_common
    steps:
      - checkout
      - run: 'sudo yarn global add greenkeeper-lockfile@2'
      - run: 'greenkeeper-lockfile-update'
      - run: 'echo lockfile_update installed greenkeeper-lockfile and ran greenkeeper-lockfile-update'
      - <<: *save

  test:
    machine: true
    steps:
      - checkout
      - run: docker build -t brunnel6/lxdhub .
      - run: docker run -it brunnel6/lxdhub test
      - run: docker run -it brunnel6/lxdhub lint

  lockfile_upload:
    <<: *job_common
    steps:
      - <<: *restore
      - run: 'sudo yarn global add greenkeeper-lockfile@2'
      - run: 'greenkeeper-lockfile-upload'
      - run: 'echo lockfile_upload ran greenkeeper-lockfile-upload'


  deploy_docker:
    machine: true
    working_directory: /tmp/lxdhub
    steps:
      - checkout
      - run: ./bin/deploy-docker.sh

  build_lxdhub_image:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /tmp/lxdhub
    steps:
      - checkout
      - run: 'sudo apt-add-repository ppa:ansible/ansible -y'
      - run: 'sudo apt update'
      - run: 'sudo apt install --yes lxd ansible'
      - run: 'cat ansible/roles/lxd_setup/files/lxd.seed | sudo lxd init --preseed'
      - run: 'lxc launch ubuntu:18.04 lxdhub'
      - run: 'ansible-playbook ansible/install-lxdhub.yml -c lxd -i lxdhub,'
      - run: 'lxc publish "local:lxdhub" --alias "lxdhub" description="lxdhub $CIRCLE_SHA1 ($(date +%Y%m%d_%H:%M))" --public'
      - run: 'lxc image export local:lxdhub /tmp/lxdhub-img --quiet'
      - store_artifacts:
          path: /tmp/lxdhub-img.tar.gz
          destination: lxdhub-img.tar.gz

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - lockfile_update
      - test:
          requires:
            - lockfile_update
      - lockfile_upload:
          requires:
            - test
      - build_lxdhub_image
      # - deploy_docker:
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v.*/
      #     requires:
      #       - test

